<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { ApiClient, ApiClientError } from '../../api/client'
import { useSessionStore } from '../../app/stores/session'
import type { DocumentSummary } from '../../types/api'
import DocumentActions from '../../components/admin/DocumentActions.vue'
import ConfirmDialog from '../../components/ConfirmDialog.vue'

const session = useSessionStore(); const client = new ApiClient('', () => session.adminToken); const documents = ref<DocumentSummary[]>([]); const error = ref(''); const loading = ref(false); const uploadBusy = ref(false); const pendingDelete = ref<DocumentSummary | null>(null); const replacementId = ref<string | null>(null); const fileInput = ref<HTMLInputElement | null>(null); const kbId = computed(() => session.activeKnowledgeBaseId)
async function load() { if (!kbId.value) return; loading.value = true; error.value = ''; try { documents.value = await client.listDocuments(kbId.value) } catch (cause) { error.value = cause instanceof ApiClientError ? cause.message : '文档列表暂时无法读取。' } finally { loading.value = false } }
async function upload(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file || !kbId.value) return; uploadBusy.value = true; try { if (replacementId.value) await client.replaceDocument(kbId.value, replacementId.value, file); else await client.uploadDocument(kbId.value, file); replacementId.value = null; await load() } catch (cause) { error.value = cause instanceof ApiClientError ? cause.message : '文档更新未完成。' } finally { uploadBusy.value = false; if (fileInput.value) fileInput.value.value = '' } }
function replaceDocument(documentId: string) { replacementId.value = documentId; fileInput.value?.click() }
async function deleteDocument() { if (!pendingDelete.value || !kbId.value) return; try { await client.deleteDocument(kbId.value, pendingDelete.value.id); pendingDelete.value = null; await load() } catch (cause) { error.value = cause instanceof ApiClientError ? cause.message : '文档删除未完成。' } }
watch(kbId, load); onMounted(load)
</script>

<template><section class="admin-page"><div class="heading"><div><span class="eyebrow">ADMIN / DOCUMENTS</span><h1>文档与更新</h1><p>当前手册中的原始文档和索引状态。</p></div><label class="upload"><input ref="fileInput" type="file" accept="application/pdf" :disabled="uploadBusy" @change="upload" />{{ uploadBusy ? '上传中…' : (replacementId ? '选择替换 PDF' : '上传 PDF') }}</label></div><p v-if="!kbId" class="empty">请先在顶部选择知识库。</p><p v-else-if="error" class="error">{{ error }}</p><div v-else class="table-wrap"><table><thead><tr><th>文件</th><th>状态</th><th>页数</th><th>chunks</th><th>操作</th></tr></thead><tbody><tr v-for="doc in documents" :key="doc.id"><td><strong>{{ doc.original_file_name }}</strong><small>{{ doc.file_hash.slice(0, 12) }} · v{{ doc.version }}</small></td><td><span class="pill">{{ doc.status }}</span><small>{{ doc.parse_status }} / {{ doc.index_status }}</small></td><td>{{ doc.page_count ?? '—' }}</td><td>{{ doc.child_chunk_count ?? 0 }}</td><td><DocumentActions :document="doc" @replace="replaceDocument" @delete="pendingDelete = doc" /></td></tr><tr v-if="!documents.length"><td colspan="5" class="empty">暂无文档。</td></tr></tbody></table></div><ConfirmDialog :open="Boolean(pendingDelete)" title="删除这份文档？" :description="`将提交删除任务：${pendingDelete?.original_file_name ?? ''}。后端会保留任务状态并执行真实权限校验。`" confirm-label="确认删除" @cancel="pendingDelete = null" @confirm="deleteDocument" /></section></template>

<style scoped>
.admin-page { max-width: 1180px; margin: 0 auto; } .heading { display: flex; justify-content: space-between; align-items: end; margin-bottom: 24px; } .eyebrow { color: var(--color-amber); font: 11px Bahnschrift, monospace; letter-spacing: .12em; } h1 { margin: 9px 0 7px; font-size: 38px; letter-spacing: -.05em; } .heading p { margin: 0; color: var(--color-muted); } .upload { display: inline-grid; place-items: center; min-height: 40px; padding: 0 14px; border-radius: var(--radius-control); color: white; background: var(--color-cobalt); font-weight: 700; cursor: pointer; } .upload input { display: none; } .table-wrap { overflow: auto; border: 1px solid var(--color-line); border-radius: var(--radius-panel); background: white; } table { width: 100%; border-collapse: collapse; min-width: 720px; } th, td { padding: 14px 16px; border-bottom: 1px solid var(--color-line); text-align: left; font-size: 13px; } th { color: var(--color-muted); background: #f6f8fa; font: 10px Bahnschrift, monospace; letter-spacing: .08em; text-transform: uppercase; } td small { display: block; margin-top: 4px; color: var(--color-muted); font-size: 11px; } .pill { display: inline-block; padding: 4px 7px; border-radius: 5px; color: var(--color-success); background: #e8f7f1; font-size: 11px; } .empty, .error { padding: 18px; color: var(--color-muted); } .error { color: var(--color-danger); }
</style>
