<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { ApiClient, ApiClientError } from '../../api/client'
import { useSessionStore } from '../../app/stores/session'
import type { GenerationSummary } from '../../types/api'
import GenerationActions from '../../components/admin/GenerationActions.vue'
import ConfirmDialog from '../../components/ConfirmDialog.vue'
const session = useSessionStore(); const client = new ApiClient('', () => session.adminToken); const generations = ref<GenerationSummary[]>([]); const error = ref(''); const result = ref(''); const busy = ref(false); const pending = ref<{ kind: 'promote' | 'rollback'; id: string } | null>(null); const diff = ref(''); const kbId = computed(() => session.activeKnowledgeBaseId)
async function load() { if (!kbId.value) return; try { generations.value = await client.listGenerations(kbId.value) } catch (cause) { error.value = cause instanceof ApiClientError ? cause.message : 'Generation 列表暂时无法读取。' } }
async function action(kind: 'validate' | 'promote' | 'rollback' | 'diff', id: string) { if (!kbId.value) return; if (kind === 'promote' || kind === 'rollback') { pending.value = { kind, id }; return } busy.value = true; try { const response = kind === 'validate' ? await client.validateGeneration(kbId.value, id) : await client.diffGeneration(kbId.value, id); if (kind === 'diff') diff.value = JSON.stringify(response, null, 2); else result.value = '验证结果已返回。' } catch (cause) { error.value = cause instanceof ApiClientError ? cause.message : 'Generation 操作未完成。' } finally { busy.value = false } }
async function confirmAction() { if (!pending.value || !kbId.value) return; busy.value = true; try { if (pending.value.kind === 'promote') await client.promoteGeneration(kbId.value, pending.value.id); else await client.rollbackGeneration(kbId.value, pending.value.id); result.value = `${pending.value.kind === 'promote' ? 'Promote' : 'Rollback'} 已提交。`; pending.value = null; await load() } catch (cause) { error.value = cause instanceof ApiClientError ? cause.message : 'Generation 操作未完成。' } finally { busy.value = false } }
watch(kbId, load); onMounted(load)
</script>

<template><section class="admin-page"><div class="heading"><div><span class="eyebrow">ADMIN / GENERATIONS</span><h1>Generation 生命周期</h1><p>验证、提升、回滚和比较索引代际；所有危险动作都需要二次确认。</p></div><button class="refresh" @click="load">刷新</button></div><p v-if="error" class="error">{{ error }}</p><p v-if="result" class="success">{{ result }}</p><p v-if="!kbId" class="empty">请先选择知识库。</p><div v-else class="generation-list"><article v-for="generation in generations" :key="generation.id" class="generation"><div class="generation-main"><div class="generation-title"><strong>{{ generation.generation }}</strong><span>{{ generation.status }}</span></div><small>{{ generation.backend }} · {{ generation.created_at || '创建时间未知' }}</small><p v-if="generation.last_error">{{ generation.last_error }}</p></div><GenerationActions :generation="generation" :busy="busy" @action="action" /></article><div v-if="!generations.length" class="empty">暂无 Generation。</div></div><pre v-if="diff" class="diff">{{ diff }}</pre><ConfirmDialog :open="Boolean(pending)" :title="pending?.kind === 'promote' ? '提升这个 Generation？' : '回滚到这个 Generation？'" :description="pending?.kind === 'promote' ? '提升会改变当前知识库的活动指针，请确认校验结果和影响范围。' : '回滚会改变当前知识库的活动指针，请确认这是经过验证的安全代际。'" :confirm-label="pending?.kind === 'promote' ? '确认 Promote' : '确认 Rollback'" @cancel="pending = null" @confirm="confirmAction" /></section></template>

<style scoped>
.admin-page { max-width: 1180px; margin: 0 auto; } .heading { display: flex; justify-content: space-between; align-items: end; margin-bottom: 24px; } .eyebrow { color: var(--color-amber); font: 11px Bahnschrift, monospace; letter-spacing: .12em; } h1 { margin: 9px 0 7px; font-size: 38px; letter-spacing: -.05em; } .heading p { margin: 0; color: var(--color-muted); } .refresh { min-height: 40px; padding: 0 13px; border: 1px solid var(--color-line); border-radius: var(--radius-control); color: var(--color-cobalt); background: white; font-weight: 700; } .generation-list { display: grid; gap: 10px; } .generation { display: flex; align-items: center; justify-content: space-between; gap: 18px; padding: 17px; border: 1px solid var(--color-line); border-radius: var(--radius-panel); background: white; } .generation-title { display: flex; align-items: center; gap: 10px; } .generation-title strong { font: 15px Bahnschrift, monospace; } .generation-title span { padding: 4px 7px; border-radius: 5px; color: var(--color-success); background: #e8f7f1; font-size: 11px; } .generation small, .generation p { color: var(--color-muted); font-size: 12px; } .diff { overflow: auto; margin-top: 18px; padding: 16px; border: 1px solid var(--color-line); background: #17212b; color: #d8e6ff; font: 12px Bahnschrift, monospace; } .empty, .error, .success { padding: 16px; color: var(--color-muted); background: white; } .error { color: var(--color-danger); } .success { color: var(--color-success); }
@media (max-width: 650px) { .generation { align-items: start; flex-direction: column; } }
</style>
