"""SQLAlchemy ORM models for KnowledgeBase, Document, and LifecycleTask."""

from __future__ import annotations

import enum
import uuid
from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _utcnow() -> datetime:
    return datetime.now(tz=UTC)


def _new_uuid() -> str:
    return uuid.uuid4().hex


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class KBStatus(enum.StrEnum):
    creating = "creating"
    ready = "ready"
    indexing = "indexing"
    rebuilding = "rebuilding"
    deleting = "deleting"
    deleted = "deleted"
    error = "error"


class DocumentStatus(enum.StrEnum):
    uploaded = "uploaded"
    parsing = "parsing"
    parsed = "parsed"
    indexing = "indexing"
    indexed = "indexed"
    rebuilding = "rebuilding"
    deleting = "deleting"
    deleted = "deleted"
    failed = "failed"


class TaskType(enum.StrEnum):
    parse = "parse"
    index = "index"
    reparse = "reparse"
    reindex = "reindex"
    rebuild = "rebuild"
    migrate_to_qdrant = "migrate_to_qdrant"
    rollback_to_nano = "rollback_to_nano"
    delete_document = "delete_document"
    delete_knowledge_base = "delete_knowledge_base"


class VectorIndexGenerationStatus(enum.StrEnum):
    shadow = "shadow"
    building = "building"
    validating = "validating"
    ready = "ready"
    active = "active"
    retired = "retired"
    archived = "archived"
    rolled_back = "rolled_back"
    failed = "failed"
    deleted = "deleted"


class TaskStatus(enum.StrEnum):
    pending = "pending"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    retrying = "retrying"
    cancelling = "cancelling"
    cancelled = "cancelled"


class UpdateOperation(enum.StrEnum):
    add = "add"
    replace = "replace"
    delete = "delete"


class UpdateJobStatus(enum.StrEnum):
    pending = "pending"
    claimed = "claimed"
    running = "running"
    building = "building"
    validating = "validating"
    ready = "ready"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"
    recovery_required = "recovery_required"
    promoted = "promoted"
    rolled_back = "rolled_back"


class ValidationRunStatus(enum.StrEnum):
    running = "running"
    passed = "passed"
    failed = "failed"
    abandoned = "abandoned"


class GCPlanStatus(enum.StrEnum):
    planned = "planned"
    approved = "approved"
    executing = "executing"
    completed = "completed"
    partial_failed = "partial_failed"
    rejected = "rejected"
    expired = "expired"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class KnowledgeBase(Base):
    __tablename__ = "knowledge_bases"

    id: Mapped[str] = mapped_column(
        String(32), primary_key=True, default=_new_uuid
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False, default="")
    description: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    status: Mapped[KBStatus] = mapped_column(
        Enum(KBStatus), nullable=False, default=KBStatus.creating
    )

    # Storage isolation — paths generated by StorageLayout, never from user input
    workspace_path: Mapped[str] = mapped_column(Text, nullable=False, default="")
    upload_path: Mapped[str] = mapped_column(Text, nullable=False, default="")
    parsed_path: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Parser / chunker snapshot
    parser_name: Mapped[str] = mapped_column(String(50), nullable=False, default="PyMuPDF")
    parser_version: Mapped[str | None] = mapped_column(String(30), nullable=True, default=None)
    chunking_strategy: Mapped[str] = mapped_column(String(50), nullable=False, default="fixed_character")
    chunking_version: Mapped[str] = mapped_column(String(20), nullable=False, default="1")
    chunking_config: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)

    # Embedding snapshot
    embedding_model: Mapped[str] = mapped_column(String(50), nullable=False, default="text-embedding-v4")
    embedding_dimension: Mapped[int] = mapped_column(Integer, nullable=False, default=1024)

    # Vector backend state. The active record carries immutable workspace and input provenance.
    vector_backend: Mapped[str] = mapped_column(String(20), nullable=False, default="nano")
    active_vector_generation_id: Mapped[str | None] = mapped_column(
        String(32),
        ForeignKey("vector_index_generations.id", use_alter=True, name="fk_kb_active_vector_generation"),
        nullable=True,
        default=None,
        index=True,
    )
    active_vector_generation: Mapped[VectorIndexGeneration | None] = relationship(
        "VectorIndexGeneration",
        foreign_keys=[active_vector_generation_id],
        post_update=True,
    )
    generation_epoch: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_rollback_target_generation_id: Mapped[str | None] = mapped_column(
        String(32),
        ForeignKey(
            "vector_index_generations.id",
            use_alter=True,
            name="fk_kb_last_rollback_generation",
        ),
        nullable=True,
        default=None,
        index=True,
    )

    # Counts (aggregated from documents / LightRAG)
    document_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    active_document_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    chunk_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    entity_count: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    relation_count: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)

    # Flags
    is_legacy_default: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    protect_from_delete: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    # Relationships
    documents: Mapped[list[Document]] = relationship(
        "Document", back_populates="knowledge_base", lazy="selectin"
    )
    tasks: Mapped[list[LifecycleTask]] = relationship(
        "LifecycleTask", back_populates="knowledge_base", lazy="selectin"
    )
    vector_generations: Mapped[list[VectorIndexGeneration]] = relationship(
        "VectorIndexGeneration",
        back_populates="knowledge_base",
        foreign_keys="VectorIndexGeneration.knowledge_base_id",
        lazy="selectin",
    )

    def __repr__(self) -> str:
        return f"<KnowledgeBase id={self.id!r} name={self.name!r} status={self.status.value!r}>"


class VectorIndexGeneration(Base):
    """Immutable storage/provenance record for one complete vector index build."""

    __tablename__ = "vector_index_generations"
    __table_args__ = (
        UniqueConstraint(
            "knowledge_base_id", "backend", "generation", name="uq_kb_vector_generation"
        ),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_uuid)
    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), nullable=False, index=True
    )
    backend: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    generation: Mapped[str] = mapped_column(String(80), nullable=False)
    status: Mapped[VectorIndexGenerationStatus] = mapped_column(
        Enum(VectorIndexGenerationStatus), nullable=False, default=VectorIndexGenerationStatus.shadow,
        index=True,
    )
    workspace_path: Mapped[str] = mapped_column(Text, nullable=False)
    collections: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)
    document_manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    child_chunks_manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    embedding_config_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    chunking_config_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    created_by_task_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("lifecycle_tasks.id"), nullable=True, index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    activated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    retired_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    protect_from_delete: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    audit_frozen: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    retention_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    content_epoch: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    validated_fingerprint: Mapped[str | None] = mapped_column(
        String(64), nullable=True
    )

    knowledge_base: Mapped[KnowledgeBase] = relationship(
        "KnowledgeBase", back_populates="vector_generations", foreign_keys=[knowledge_base_id]
    )


class Document(Base):
    __tablename__ = "documents"
    __table_args__ = (
        UniqueConstraint("knowledge_base_id", "file_hash", "is_active", name="uq_kb_active_hash"),
    )

    id: Mapped[str] = mapped_column(
        String(32), primary_key=True, default=_new_uuid
    )
    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), nullable=False, index=True
    )

    # File info
    original_file_name: Mapped[str] = mapped_column(String(500), nullable=False)
    logical_name: Mapped[str | None] = mapped_column(String(500), nullable=True, default=None)
    source_type: Mapped[str | None] = mapped_column(String(50), nullable=True, default=None)
    stored_file_name: Mapped[str] = mapped_column(String(200), nullable=False)
    file_path: Mapped[str] = mapped_column(Text, nullable=False, default="")
    file_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    file_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    mime_type: Mapped[str] = mapped_column(String(100), nullable=False, default="application/pdf")

    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Status
    status: Mapped[DocumentStatus] = mapped_column(
        Enum(DocumentStatus), nullable=False, default=DocumentStatus.uploaded
    )
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    parse_status: Mapped[str] = mapped_column(String(30), nullable=False, default="pending")
    index_status: Mapped[str] = mapped_column(String(30), nullable=False, default="pending")

    # Parser / chunker snapshot
    parser_name: Mapped[str] = mapped_column(String(50), nullable=False, default="PyMuPDF")
    parser_version: Mapped[str | None] = mapped_column(String(30), nullable=True, default=None)
    chunking_strategy: Mapped[str] = mapped_column(String(50), nullable=False, default="fixed_character")
    chunking_version: Mapped[str] = mapped_column(String(20), nullable=False, default="1")

    # Counts
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True, default=None)
    parent_chunk_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    child_chunk_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )
    indexed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    # Relationships
    knowledge_base: Mapped[KnowledgeBase] = relationship(
        "KnowledgeBase", back_populates="documents"
    )
    tasks: Mapped[list[LifecycleTask]] = relationship(
        "LifecycleTask", back_populates="document", lazy="selectin"
    )

    def __repr__(self) -> str:
        return (
            f"<Document id={self.id!r} kb={self.knowledge_base_id!r} "
            f"file={self.original_file_name!r} status={self.status.value!r}>"
        )


class LifecycleTask(Base):
    __tablename__ = "lifecycle_tasks"

    id: Mapped[str] = mapped_column(
        String(32), primary_key=True, default=_new_uuid
    )
    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), nullable=False, index=True
    )
    document_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("documents.id"), nullable=True, index=True
    )

    task_type: Mapped[TaskType] = mapped_column(Enum(TaskType), nullable=False)
    status: Mapped[TaskStatus] = mapped_column(
        Enum(TaskStatus), nullable=False, default=TaskStatus.pending
    )

    progress: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    current_stage: Mapped[str | None] = mapped_column(String(200), nullable=True, default=None)

    attempt: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)

    # Structured payload / result (JSON)
    payload: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)
    result: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    error_code: Mapped[str | None] = mapped_column(String(50), nullable=True, default=None)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)

    # Cleanup steps (JSON array of {step_name, status, attempt, error, completed_at})
    cleanup_steps: Mapped[list | None] = mapped_column(JSON, nullable=True, default=None)

    # Relationships
    knowledge_base: Mapped[KnowledgeBase] = relationship(
        "KnowledgeBase", back_populates="tasks"
    )
    document: Mapped[Document | None] = relationship(
        "Document", back_populates="tasks"
    )

    def __repr__(self) -> str:
        return (
            f"<LifecycleTask id={self.id!r} type={self.task_type.value!r} "
            f"status={self.status.value!r}>"
        )


class UpdateJob(Base):
    """One incremental knowledge-base update operation (add / replace / delete).

    Each job owns a candidate generation.  The candidate inherits unchanged
    documents from the active generation and only processes the changed
    document.  Promote/rollback operate on generation pointers; physical data
    cleanup is an explicit maintenance task and never part of this flow.
    """

    __tablename__ = "update_jobs"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_uuid)
    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), nullable=False, index=True
    )
    base_generation_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("vector_index_generations.id"), nullable=True, index=True
    )
    candidate_generation_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("vector_index_generations.id"), nullable=True, index=True
    )
    operation: Mapped[UpdateOperation] = mapped_column(Enum(UpdateOperation), nullable=False)
    document_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("documents.id"), nullable=True, index=True
    )
    old_content_sha256: Mapped[str | None] = mapped_column(String(64), nullable=True)
    new_content_sha256: Mapped[str | None] = mapped_column(String(64), nullable=True)
    status: Mapped[UpdateJobStatus] = mapped_column(
        Enum(UpdateJobStatus), nullable=False, default=UpdateJobStatus.pending, index=True
    )
    current_stage: Mapped[str | None] = mapped_column(String(200), nullable=True)
    retry_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    error_code: Mapped[str | None] = mapped_column(String(50), nullable=True)
    sanitized_error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    request_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    created_by: Mapped[str] = mapped_column(String(50), nullable=False, default="api")
    approved_by: Mapped[str | None] = mapped_column(String(50), nullable=True)
    metrics: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)
    result: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)
    worker_id: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    lease_token: Mapped[str | None] = mapped_column(String(64), nullable=True)
    fencing_token: Mapped[int | None] = mapped_column(Integer, nullable=True)
    claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    heartbeat_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    lease_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, index=True
    )
    attempt: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)
    checkpoint: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    knowledge_base: Mapped[KnowledgeBase] = relationship(
        "KnowledgeBase", foreign_keys=[knowledge_base_id]
    )
    document: Mapped[Document | None] = relationship(
        "Document", foreign_keys=[document_id]
    )
    base_generation: Mapped[VectorIndexGeneration | None] = relationship(
        "VectorIndexGeneration", foreign_keys=[base_generation_id]
    )
    candidate_generation: Mapped[VectorIndexGeneration | None] = relationship(
        "VectorIndexGeneration", foreign_keys=[candidate_generation_id]
    )


class ValidationRun(Base):
    """Append-only canonical validation evidence for one Generation."""

    __tablename__ = "validation_runs"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_uuid)
    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), nullable=False, index=True
    )
    generation_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("vector_index_generations.id"), nullable=False, index=True
    )
    status: Mapped[ValidationRunStatus] = mapped_column(
        Enum(ValidationRunStatus),
        nullable=False,
        default=ValidationRunStatus.running,
        index=True,
    )
    golden_set_version: Mapped[str] = mapped_column(String(100), nullable=False)
    golden_set_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    runner_version: Mapped[str] = mapped_column(String(100), nullable=False)
    app_git_commit: Mapped[str] = mapped_column(String(40), nullable=False)
    configured_model: Mapped[str] = mapped_column(String(100), nullable=False)
    strategy_fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    generation_manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    qdrant_content_fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    document_registry_fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    generation_content_epoch: Mapped[int] = mapped_column(Integer, nullable=False)
    metrics: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    passed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    result_artifact_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    result_artifact_sha256: Mapped[str | None] = mapped_column(String(64), nullable=True)
    actor: Mapped[str] = mapped_column(String(50), nullable=False)
    request_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )


class KBOperationLease(Base):
    """Durable one-writer lease and monotonic fencing counter for a KB."""

    __tablename__ = "kb_operation_leases"

    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), primary_key=True
    )
    lock_owner: Mapped[str | None] = mapped_column(String(100), nullable=True)
    lease_token: Mapped[str | None] = mapped_column(String(64), nullable=True)
    fencing_token: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    acquired_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    heartbeat_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True, index=True)
    operation: Mapped[str | None] = mapped_column(String(50), nullable=True)
    job_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("update_jobs.id"), nullable=True, index=True
    )


class GCPlan(Base):
    """Immutable dry-run plan plus explicit approval and execution evidence."""

    __tablename__ = "gc_plans"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_uuid)
    knowledge_base_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("knowledge_bases.id"), nullable=False, index=True
    )
    status: Mapped[GCPlanStatus] = mapped_column(
        Enum(GCPlanStatus), nullable=False, default=GCPlanStatus.planned, index=True
    )
    policy: Mapped[dict] = mapped_column(JSON, nullable=False)
    items: Mapped[list] = mapped_column(JSON, nullable=False)
    manifest_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    created_by: Mapped[str] = mapped_column(String(50), nullable=False)
    approved_by: Mapped[str | None] = mapped_column(String(50), nullable=True)
    result: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    executed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class RetrievalTraceRecord(Base):
    """Insert-only retrieval diagnosis payload keyed by the ordinary request ID."""

    __tablename__ = "retrieval_traces"

    request_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    trace_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    knowledge_base_id: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    generation_id: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    trace_version: Mapped[str] = mapped_column(String(80), nullable=False)
    payload: Mapped[dict] = mapped_column(JSON, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )


class AnswerFeedbackRecord(Base):
    """Persisted answer snapshot and optional user/reviewer labels.

    This table is intentionally separate from the TTL-bounded retrieval trace.
    It contains only the bounded data needed to review an answer later.
    """

    __tablename__ = "answer_feedback"
    __table_args__ = (
        UniqueConstraint(
            "request_id", name="uq_answer_feedback_request_id"
        ),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_uuid)
    request_id: Mapped[str] = mapped_column(
        String(64), nullable=False, index=True
    )
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    generation_id: Mapped[str | None] = mapped_column(
        String(32), nullable=True, index=True
    )
    knowledge_base_id: Mapped[str | None] = mapped_column(
        String(32), nullable=True, index=True
    )
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str] = mapped_column(Text, nullable=False)
    answer_status: Mapped[str] = mapped_column(
        String(32), nullable=False, index=True
    )
    feedback_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    feedback_reason: Mapped[str | None] = mapped_column(String(64), nullable=True)
    feedback_comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    citations: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    retrieved_chunks: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    answer_correct: Mapped[str | None] = mapped_column(String(20), nullable=True)
    answer_complete: Mapped[str | None] = mapped_column(String(20), nullable=True)
    citation_supported: Mapped[str | None] = mapped_column(String(20), nullable=True)
    refusal_appropriate: Mapped[str | None] = mapped_column(String(20), nullable=True)
    root_cause: Mapped[str | None] = mapped_column(String(64), nullable=True)
    review_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
