"""create_lifecycle_tables

Revision ID: d7e568c55ad8
Revises: 
Create Date: 2026-07-31 00:11:04.000980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e568c55ad8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('creating', 'ready', 'indexing', 'rebuilding', 'deleting', 'deleted', 'error', name='kbstatus'), nullable=False),
    sa.Column('workspace_path', sa.Text(), nullable=False),
    sa.Column('upload_path', sa.Text(), nullable=False),
    sa.Column('parsed_path', sa.Text(), nullable=False),
    sa.Column('parser_name', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=30), nullable=True),
    sa.Column('chunking_strategy', sa.String(length=50), nullable=False),
    sa.Column('chunking_version', sa.String(length=20), nullable=False),
    sa.Column('chunking_config', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=50), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('active_document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=True),
    sa.Column('relation_count', sa.Integer(), nullable=True),
    sa.Column('is_legacy_default', sa.Boolean(), nullable=False),
    sa.Column('protect_from_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=32), nullable=False),
    sa.Column('original_file_name', sa.String(length=500), nullable=False),
    sa.Column('stored_file_name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'parsing', 'parsed', 'indexing', 'indexed', 'rebuilding', 'deleting', 'deleted', 'failed', name='documentstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parse_status', sa.String(length=30), nullable=False),
    sa.Column('index_status', sa.String(length=30), nullable=False),
    sa.Column('parser_name', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=30), nullable=True),
    sa.Column('chunking_strategy', sa.String(length=50), nullable=False),
    sa.Column('chunking_version', sa.String(length=20), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parent_chunk_count', sa.Integer(), nullable=False),
    sa.Column('child_chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'file_hash', 'is_active', name='uq_kb_active_hash')
    )
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_table('lifecycle_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('task_type', sa.Enum('parse', 'index', 'reparse', 'reindex', 'rebuild', 'delete_document', 'delete_knowledge_base', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'retrying', 'cancelling', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=200), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cleanup_steps', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_tasks_document_id'), 'lifecycle_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_lifecycle_tasks_knowledge_base_id'), 'lifecycle_tasks', ['knowledge_base_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lifecycle_tasks_knowledge_base_id'), table_name='lifecycle_tasks')
    op.drop_index(op.f('ix_lifecycle_tasks_document_id'), table_name='lifecycle_tasks')
    op.drop_table('lifecycle_tasks')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
