<script setup lang="ts">
import { ref } from 'vue'
const emit = defineEmits<{ overview: []; search: [query: string, hops: 1 | 2]; settings: [settings: { showNodeLabels: boolean; showEdgeLabels: boolean }] }>()
const query = ref(''); const hops = ref<1 | 2>(1); const advanced = ref(false); const showNodeLabels = ref(true); const showEdgeLabels = ref(false)
const shortcuts = ['离心泵', '轴承', '机械密封', '振动']
function search(value = query.value) { const clean = value.trim(); if (!clean) return emit('overview'); query.value = clean; emit('search', clean, hops.value) }
</script>

<template>
  <div class="filters"><div class="filter-row"><div class="search-box"><span>⌕</span><input v-model="query" placeholder="搜索实体或现象" @keydown.enter="search()" /><button @click="search()">搜索</button></div><button class="overview" @click="emit('overview')">全局概览</button></div><div class="shortcut-row"><span>常用实体</span><button v-for="shortcut in shortcuts" :key="shortcut" @click="search(shortcut)">{{ shortcut }}</button><label>关系范围<select v-model="hops"><option :value="1">1 跳</option><option :value="2">2 跳</option></select></label><button class="advanced-toggle" @click="advanced = !advanced">{{ advanced ? '收起设置' : '显示设置' }}</button></div><div v-if="advanced" class="advanced"><span>节点与边显示保持只读；点击节点可聚焦其邻居。</span><label><input v-model="showNodeLabels" type="checkbox" @change="emit('settings', { showNodeLabels, showEdgeLabels })" />显示节点标签</label><label><input v-model="showEdgeLabels" type="checkbox" @change="emit('settings', { showNodeLabels, showEdgeLabels })" />显示关系标签</label></div></div>
</template>

<style scoped>
.filters { padding: 16px; border: 1px solid var(--color-line); border-radius: var(--radius-panel); background: var(--color-surface); } .filter-row { display: flex; gap: 10px; } .search-box { display: flex; flex: 1; align-items: center; border: 1px solid var(--color-line); border-radius: var(--radius-control); overflow: hidden; } .search-box span { padding: 0 10px; color: var(--color-muted); font-size: 20px; } input { flex: 1; min-width: 0; border: 0; outline: 0; } .search-box button, .overview { min-width: 74px; border: 0; color: white; background: var(--color-cobalt); font-weight: 700; } .overview { border-radius: var(--radius-control); } .shortcut-row { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; margin-top: 12px; color: var(--color-muted); font-size: 12px; } .shortcut-row > button { min-height: 32px; padding: 0 9px; border: 1px solid var(--color-line); border-radius: 7px; color: var(--color-ink); background: white; } .shortcut-row > button:hover, .advanced-toggle:hover { color: var(--color-cobalt); border-color: #aac4f6; } .shortcut-row label { display: flex; align-items: center; gap: 5px; margin-left: auto; } select { min-height: 32px; border: 1px solid var(--color-line); border-radius: 7px; } .advanced-toggle { border: 0 !important; color: var(--color-cobalt) !important; background: transparent !important; } .advanced { display: flex; flex-wrap: wrap; gap: 14px; margin-top: 13px; padding-top: 13px; border-top: 1px solid var(--color-line); color: var(--color-muted); font-size: 12px; } .advanced label { color: var(--color-ink); } @media (max-width: 600px) { .filter-row { display: grid; grid-template-columns: 1fr; } .overview { min-height: 44px; } .shortcut-row label { margin-left: 0; } }
</style>
